In [12]:
import numpy as np
a_array = np.array([[0,1],[2,3],[4,5]])
b_array = np.array([[0,1,2,3],[4,5,6,7]])
c_array = np.dot(a_array, b_array)
print(c_array)

max = c_array.max()
print(str(max))


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
