In [5]:
import numpy as np
A = np.array([[0, 1], [2, 3], [4, 5]])
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
# 積の計算
product = np.dot(A,B)
product

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [8]:
# 最大値の出力
product.max()

np.int64(47)