In [12]:
import numpy as np

A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

print(A)
print(B)

C = np.dot(A, B)
print(C)

D = np.max(C)
print(D)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
